# Generated by DBDiff
# On 11/12/2021 08:39:53 pm

#---------- UP ----------
CREATE TABLE `helloworld` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
#---------- DOWN ----------
